[package]
name = "ccmemcached"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = "4.5.34"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
